const actionTypes = {
  ADD_TODO: 'ADD_TODO',
  REMOVE: 'REMOVE',
  LIST_TODOS: 'LIST_TODOS',
  DESTROY_TODO: 'DESTROY_TODO',
  COMPLETED_TODO: 'COMPLETED_TODO',
  COMPLETED_TODO_LIST: 'COMPLETED_TODO_LIST',
  INCOMPLETE_TODO_LIST: 'INCOMPLETE_TODO_LIST',
  SHOW_ALL: 'SHOW_ALL',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER'
};

export default actionTypes;
